// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeU9z19PtpHdGHjfK54fA_L5M2pChBbWQ',
    appId: '1:318837711922:web:fa746859b1cf576499882b',
    messagingSenderId: '318837711922',
    projectId: 'mytodolist-32469',
    authDomain: 'mytodolist-32469.firebaseapp.com',
    databaseURL: 'https://mytodolist-32469.firebaseio.com',
    storageBucket: 'mytodolist-32469.firebasestorage.app',
    measurementId: 'G-H9Q1RSJGQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPwRHAsnZE1-n-Aw9FKOKk9PI7rx-22E',
    appId: '1:318837711922:android:ff1caace1e78730399882b',
    messagingSenderId: '318837711922',
    projectId: 'mytodolist-32469',
    databaseURL: 'https://mytodolist-32469.firebaseio.com',
    storageBucket: 'mytodolist-32469.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-QL0VGtcLSSzSQSnOLwuLzz6BSeFmOE',
    appId: '1:318837711922:ios:432b7f7d079360d099882b',
    messagingSenderId: '318837711922',
    projectId: 'mytodolist-32469',
    databaseURL: 'https://mytodolist-32469.firebaseio.com',
    storageBucket: 'mytodolist-32469.firebasestorage.app',
    iosBundleId: 'com.kihoonee.daycounterv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-QL0VGtcLSSzSQSnOLwuLzz6BSeFmOE',
    appId: '1:318837711922:ios:432b7f7d079360d099882b',
    messagingSenderId: '318837711922',
    projectId: 'mytodolist-32469',
    databaseURL: 'https://mytodolist-32469.firebaseio.com',
    storageBucket: 'mytodolist-32469.firebasestorage.app',
    iosBundleId: 'com.kihoonee.daycounterv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeU9z19PtpHdGHjfK54fA_L5M2pChBbWQ',
    appId: '1:318837711922:web:0ff9cfd6e737b98199882b',
    messagingSenderId: '318837711922',
    projectId: 'mytodolist-32469',
    authDomain: 'mytodolist-32469.firebaseapp.com',
    databaseURL: 'https://mytodolist-32469.firebaseio.com',
    storageBucket: 'mytodolist-32469.firebasestorage.app',
    measurementId: 'G-YL1HQXVPGV',
  );
}
