// Mocks generated by Mockito 5.4.6 from annotations
// in day_counter/test/features/events/data/repositories/event_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:day_counter/features/events/data/datasources/event_local_data_source.dart'
    as _i2;
import 'package:day_counter/features/events/domain/event.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EventLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventLocalDataSource extends _i1.Mock
    implements _i2.EventLocalDataSource {
  MockEventLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Event>> getLastEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getLastEvents, []),
            returnValue: _i3.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i3.Future<List<_i4.Event>>);

  @override
  _i3.Future<void> cacheEvents(List<_i4.Event>? events) =>
      (super.noSuchMethod(
            Invocation.method(#cacheEvents, [events]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertEvent(_i4.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEvent, [event]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvent, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
